# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'MyWeather' do
	pod 'Cartography', '0.6.0'
	pod 'Alamofire', '3.1.3'
	pod 'SwiftyJSON', '2.3.2'
	pod 'WeatherIconsKit', :git => 'git@github.com:gscalzo/WeatherIconsKit.git'
	pod 'FlickrKit', '1.0.7'
	pod 'FXBlurView', '1.6.4'
	pod 'LatoFont', :git => 'https://github.com/gscalzo/LatoFont.git'
end

target 'MyWeatherTests' do

end

