# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'SampleList' do
	pod 'FontAwesomeKit', :git => "https://github.com/gscalzo/FontAwesomeKit.git"
	pod 'LatoFont', :git => "https://github.com/gscalzo/LatoFont.git"
	pod 'Cartography', '0.6.0'
	pod 'MGSwipeTableCell', '1.3.5'
end

target 'SampleListTests' do

end

